it_company_task_manager/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from it_company_task_manager import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task-manager")),
    path("accounts/", include("django.contrib.auth.urls")),
]

app_name = "task_manager"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_manager/urls.py
from django.urls import path, include

from task_manager.views import (
    index,
    TaskListView,
    TaskDetailView,
    PositionListView,
    PositionListDetailView,
    WorkerListView,
    WorkerDetailView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    toggle_assign_to_task,
    take_task_to_work,
    mark_task_as_done,
    return_task_for_revision,
)


urlpatterns = [
    path("index/", index, name="index"),
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
    path(
        "tasks/<int:pk>/take-task-to-work/",
        take_task_to_work,
        name="take-task-to-work",
    ),
    path(
        "tasks/<int:pk>/mark-task-as-done/",
        mark_task_as_done,
        name="mark-task-as-done",
    ),
    path(
        "tasks/<int:pk>/return-task-for-revision/",
        return_task_for_revision,
        name="return-task-for-revision",
    ),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path(
        "positions/<int:pk>/", PositionListDetailView.as_view(), name="position-detail"
    ),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path(
        "task-types/<int:pk>/",
        TaskTypeDetailView.as_view(),
        name="task-type-detail",
    ),
    path("task-types/create/", TaskTypeCreateView.as_view(), name="task-types-create"),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-types-update",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-types-delete",
    ),
]


app_name = "task_manager"

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <div class="container-fluid col-md-2">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
        </li>
      {% endif %}
      <li class="page-item active">
        <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
        </li>

      {% endif %}
    </ul>

  </div>
{% endif %}

templates/includes/search.html
<form action="" method="get" class="form-inline my-2 my-lg-0 ">
    {{ search_form.as_div }}
   <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">🔍</button>
</form>

templates/includes/sidebar.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary active">
  <a class="navbar-brand btn-lg" href="{% url "task-manager:index" %}">Task Manager</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item btn-lg ">
        <a class="nav-link" href="{% url "task-manager:task-list" %}">Tasks</a>
      </li>
      <li class="nav-item btn-lg ">
        <a class="nav-link" href="{% url "task-manager:worker-list" %}">Workers</a>
      </li>


      <li class="nav-item btn-lg ">
        <a class="nav-link" href="{% url "task-manager:position-list" %}">Positions</a>
      </li>

      <li class="nav-item btn-lg ">
        <a class="nav-link" href="{% url "task-manager:task-type-list" %}">Task Types</a>
      </li>
    </ul>

    {% if search_form %}
      {% include "includes/search.html" %}
    {% endif %}

    {% if user.is_authenticated %}
      <span class="navbar-text">
        <a class="nav-link" href="{{ user.get_absolute_url }}">User: {{ user.get_username }}</a>
      </span>

      <span class="navbar-text">
        <a class="nav-link" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
      </span>

    {% else %}
      <span class="navbar-text">
        <a class="nav-link" href="{% url 'task-manager:worker-create'%}?next={{request.path}}">Registration</a>
      </span>

      <span class="navbar-text">
        <a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Login</a>
      </span>

      {% endif %}

  </div>
</nav>