it_company_task_manager/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from it_company_task_manager import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task_manager.urls", namespace="task-manager")),
    path("accounts/", include("django.contrib.auth.urls")),
]

app_name = "task_manager"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task_manager/urls.py
from django.urls import path, include

from task_manager.views import (
    index,
    TaskListView,
    TaskDetailView,
    PositionListView,
    PositionListDetailView,
    WorkerListView,
    WorkerDetailView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    toggle_assign_to_task,
    take_task_to_work,
    mark_task_as_done,
    return_task_for_revision,
)


urlpatterns = [
    path("index/", index, name="index"),
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
    path(
        "tasks/<int:pk>/take-task-to-work/",
        take_task_to_work,
        name="take-task-to-work",
    ),
    path(
        "tasks/<int:pk>/mark-task-as-done/",
        mark_task_as_done,
        name="mark-task-as-done",
    ),
    path(
        "tasks/<int:pk>/return-task-for-revision/",
        return_task_for_revision,
        name="return-task-for-revision",
    ),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path(
        "positions/<int:pk>/", PositionListDetailView.as_view(), name="position-detail"
    ),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("task-types/", TaskTypeListView.as_view(), name="task-type-list"),
    path(
        "task-types/<int:pk>/",
        TaskTypeDetailView.as_view(),
        name="task-type-detail",
    ),
    path("task-types/create/", TaskTypeCreateView.as_view(), name="task-types-create"),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-types-update",
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-types-delete",
    ),
]


app_name = "task_manager"

task_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Position(models.Model):
    name = models.CharField(max_length=63, unique=True)
    duties = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=63, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    photo = models.ImageField(upload_to="images/%Y/%m/%d", blank=True, null=True)
    position = models.ForeignKey(
        Position, on_delete=models.CASCADE, blank=True, null=True
    )

    @property
    def photo_url(self):
        if self.photo and hasattr(self.photo, "url"):
            return self.photo.url

    class Meta:
        ordering = ["position"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse("task-manager:worker-detail", kwargs={"pk": self.pk})


class Task(models.Model):
    PRIORITIES = (
        ("High", "One week"),
        ("Medium", "One month"),
        ("Low", "Three month"),
        ("Absent", "Free time"),
    )

    STATUS = (
        ("not_done", "all tasks"),
        ("in_progress", "tasks that are being worked on"),
        ("approved", "completed tasks"),
    )

    name = models.CharField(max_length=63)
    description = models.TextField(blank=True, null=True)
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=63, choices=PRIORITIES)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(Worker)
    status = models.CharField(max_length=63, choices=STATUS, null=True, blank=True)

    class Meta:
        ordering = ["priority"]

    def __str__(self):
        return self.name

task_manager/forms.py
import django
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError

from task_manager.models import Worker, Task


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )
    description = forms.CharField(max_length=255)
    deadline = forms.DateInput()


    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            'deadline': forms.DateInput(
                attrs={'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)', 'class': 'form-control'},
            )
        }

    def clean_name(self) -> str:
        name = self.cleaned_data.get("name", "")
        if len(name.split()) > 10:
            raise ValidationError("Not more than 10 words!")
        return name


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search worker....",
                "class": "form-control mr-sm-2",
                "type": "search",
                "aria-label": "Search",
            }
        ),
    )


class WorkerCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
            "last_login",
            "photo",
            "first_name",
            "last_name",
            "position",
            "email",
            "is_superuser",
            "user_permissions",
            "is_staff",
            "is_active",
        )


class WorkerUpdateForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = Worker

task_manager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import generic

from task_manager.forms import (
    WorkerCreateForm,
    WorkerUpdateForm,
    WorkerSearchForm,
    # TaskSearchForm,
    TaskForm,
)
from task_manager.models import Worker, Task, TaskType, Position


def index(request):
    """View function for the home page of the site."""

    num_tasks = Task.objects.count()
    num_solved_task = Task.objects.filter(is_completed=True).count()
    not_solved = num_tasks - num_solved_task

    num_visits = request.session.get("num_visits", 0)

    request.session["num_visits"] = num_visits + 1

    context = {
        "not_solved": not_solved,
        "num_tasks": num_tasks,
        "num_solved_task": num_solved_task,
        "num_visits": num_visits + 1,
    }

    return render(request, "task_manager/index.html", context=context)


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)

        context["not_done"] = list(Task.objects.filter(status="not_done"))
        context["in_progress"] = list(Task.objects.filter(status="in_progress"))
        context["approved"] = list(Task.objects.filter(status="approved"))

        return context


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")
    form_class = TaskForm


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task

    success_url = reverse_lazy("task_manager:task-list")
    form_class = TaskForm


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 4


class PositionListDetailView(LoginRequiredMixin, generic.DetailView):
    model = Position


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task_manager:position-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        queryset = Worker.objects.all().select_related("position")
        form = WorkerSearchForm(self.request.GET)
        return (
            queryset.filter(username__icontains=form.cleaned_data["username"])
            if form.is_valid()
            else queryset.all()
        )


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker


class WorkerCreateView(generic.CreateView):
    model = Worker
    form_class = WorkerCreateForm


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("task-manager:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("task-manager:worker-list")


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    paginate_by = 6


class TaskTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = TaskType


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("task_manager:task-type-list")


@login_required
def toggle_assign_to_task(request, pk):
    worker = Worker.objects.get(id=request.user.id)
    if Task.objects.get(id=pk) in worker.task_set.all():
        worker.task_set.remove(pk)
    else:
        worker.task_set.add(pk)
    return HttpResponseRedirect(reverse_lazy("task-manager:task-detail", args=[pk]))


def take_task_to_work(request, pk):
    task = Task.objects.get(pk=pk)
    task.status = "in_progress"
    task.save()
    return HttpResponseRedirect(reverse_lazy("task-manager:task-detail", args=[pk]))


def mark_task_as_done(request, pk):
    task = Task.objects.get(pk=pk)
    task.status = "approved"
    task.is_completed = True
    task.save()

    return HttpResponseRedirect(reverse_lazy("task-manager:task-detail", args=[pk]))


def return_task_for_revision(request, pk):
    task = Task.objects.get(pk=pk)
    task.status = "in_progress"
    task.is_completed = False
    task.save()
    return HttpResponseRedirect(reverse_lazy("task-manager:task-detail", args=[pk]))

templates/task_manager/index.html
{% extends "base.html" %}
{% block content %}

<div class="parent">
    <div class="block">
      <h1>
        <span>Our team:</span>
        <div class="message">
          <div class="word1">{{ num_tasks }} tasks</div>
          <div class="word2">{{ num_solved_task }} done</div>
          <div class="word3">{{ not_solved }} decide </div>
        </div>
       </h1>
    </div>
</div>

{% endblock %}

templates/task_manager/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2 class="container">are you sure you want to delete the position, it will lead to the deletion of all employees in this position?</h2>
  <form action="" method="post">
    {% csrf_token %}

  <div class="container">
    <input type="submit" value="Yes" class="btn btn-danger container">
    <a href="{% url "task_manager:position-list"  %}" class="btn btn-secondary container">No</a>
  </div>

  </form>
{% endblock %}

templates/task_manager/position_detail.html
{% extends "base.html" %}

{% block content %}



  <br>

    <div class="card text-white bg-dark mb-3 container" style="max-width: 70rem;">
    <div class="card-header text-uppercase">{{ position.id }}: {{ position.name }}</div>
    <div class="card-body">
      <h5 class="card-title">Duties of the position: {{ position.duties }}</h5>
      <br>
      <h5 class="card-title">Workers on the position: </h5>
      {% if position %}
      {% for worker in position.worker_set.all %}
        <p class="card-text container"><a href="{% url "task-manager:worker-detail" pk=worker.pk %}"> {{ worker.first_name }} {{ worker.last_name }} ({{ worker.username }}) </a></p>
      {% endfor %}
      {% else %}
        <p class="card-text container"> There are no workers on the type.</p>
      {% endif %}

    </div>
  </div>

  <div class="container">
    <a class="btn btn-warning btn-lg" href="{% url "task_manager:position-update" pk=position.pk %}">Update</a>
    <a class="btn btn-danger btn-lg" href="{% url "task_manager:position-delete" pk=position.pk %}">Delete</a>
  </div>

{% endblock %}

templates/task_manager/position_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} position </h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

{% block footer %}
{% endblock %}

templates/task_manager/task_detail.html
{% extends "base.html" %}

{% block content %}
  <br>
  <div class="card text-white bg-dark mb-3 container" style="max-width: 70rem;">
    <div class="card-header text-uppercase">{{ task.id }}: {{ task.name }} <span class="float-right">{% if  task.is_completed %} ✅ {% else %} ❌ {% endif %}</span></div>
    <div class="card-body">
      <h5 class="card-title">Task description: {{ task.description }}</h5>
      <h6 class="card-title">This task type {{ task.task_type }} must be completed by {{ task.deadline}}, this task has a
        {{ task.priority }} priority.</h6>
      <br>
      <h5 class="card-title">Employees are assigned to perform tasks: </h5>
      {% if task.assignees.all %}
      {% for worker in task.assignees.all %}
        <p class="card-text container">
          <a href="{% url "task-manager:worker-detail" pk=worker.pk %}">{{ worker.first_name }} {{ worker.last_name.name }} ({{ worker.username }})</a>
        </p>
      {% endfor %}
      {% else %}
        <p class="card-text container"> There are no workers on the type.</p>
      {% endif %}

    </div>
  </div>

  <div class="container">
      {% if task in user.task_set.all %}
      <a class="btn btn-secondary btn-lg" href="{% url 'task-manager:toggle-task-assign' pk=task.id %}">
        Delete me from this task
      </a>
    {% else %}
      <a class="btn btn-secondary btn-lg" href="{% url 'task-manager:toggle-task-assign' pk=task.id %}">
        Assign me from this task
      </a>
    {% endif %}

    {% if task.status == "not_done" %}
      <a class="btn btn-secondary btn-lg" href="{% url 'task-manager:take-task-to-work' pk=task.id %}">
        Take task to work
      </a>
    {% elif task.status == "approved" %}
      <a class="btn btn-secondary btn-lg" href="{% url 'task-manager:return-task-for-revision' pk=task.id %}">
        Return task to revision
      </a>
    {% elif task.status == "in_progress" %}
      <a class="btn btn-secondary btn-lg" href="{% url 'task-manager:mark-task-as-done' pk=task.id %}">
        Mark task as done
      </a>
    {% endif %}

  </div>
  <br>
  <div class="container">
    <a class="btn btn-warning btn-lg" href="{% url "task_manager:task-update" pk=task.pk %}">Update</a>
    <a class="btn btn-danger btn-lg" href="{% url "task_manager:task-delete" pk=task.pk %}">Delete</a>
  </div>

{% endblock %}

templates/task_manager/task_list.html
{% extends "base.html" %}

{% block content %}

    <br>
  <a class="btn btn-success" href="{% url 'task_manager:task-create' %}" style="margin-left: 5%;">
      Create new task
  </a>
  <p></p>

<div id="header">Magic task board</div>


<div id="left">
  <h4>Not done:</h4>
  {% for n_d in not_done %}
    <a href="{% url "task_manager:task-detail" pk=n_d.pk %}" style="text-decoration: none;">
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">{{ n_d.name }} ({{ n_d.status }}) Type:{{ n_d.task_type }} Priority: {{ n_d.priority }}</h4>
      <p>{{ n_d.description}}</p>
      <hr>
      <p class="mb-0">The task must be completed by {{ n_d.deadline }}</p>
    </div>
    </a>
  {% endfor %}
</div>

<div id="right">
<h4>Approved:</h4>
  {% for a_p in approved %}
    <a href="{% url "task_manager:task-detail" pk=a_p.pk %}" style="text-decoration: none;">
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">{{ a_p.name }} ({{ a_p.status }}) Type:{{ a_p.task_type }} Priority: {{ a_p.priority }}</h4>
      <p>{{ a_p.description}}</p>
      <hr>
      <p class="mb-0">The task must be completed by {{ a_p.deadline }}</p>
    </div>
    </a>
  {% endfor %}
</div>

<div id="middle">
  <h4>In progress:</h4>
  {% for i_p in in_progress %}
    <a href="{% url "task_manager:task-detail" pk=i_p.pk %}" style="text-decoration: none;">
    <div class="alert alert-warning" role="alert">
      <h4 class="alert-heading">{{ i_p.name }} ({{ i_p.status }}) Type:{{ i_p.task_type }} Priority: {{ i_p.priority }}</h4>
      <p>{{ i_p.description}}</p>
      <hr>
       <p class="mb-0">The task must be completed by {{ i_p.deadline }}</p>
    </div>
    </a>
  {% endfor %}
</div>


{% endblock %}
{% block footer %}
{% endblock %}

templates/task_manager/tasktype_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2 class="container">Are you sure you want to delete a task type, this will delete tasks associated with the task type</h2>
  <form action="" method="post">
    {% csrf_token %}

  <div class="container">
    <input type="submit" value="Yes" class="btn btn-danger container">
    <a href="{% url "task_manager:task-type-list"  %}" class="btn btn-secondary container">No</a>
  </div>

  </form>
{% endblock %}

templates/task_manager/tasktype_detail.html
{% extends "base.html" %}

{% block content %}
  <br>

  <div class="card text-white bg-dark mb-3 container" style="max-width: 70rem;">
    <div class="card-header text-uppercase">{{ tasktype.id }}: {{ tasktype.name }}</div>
    <div class="card-body">
      <h5 class="card-title">Tasks of this type:</h5>
      {% if tasktype.task_set.all %}
      {% for task in tasktype.task_set.all %}
        <p class="card-text container"> <a href="{% url "task-manager:task-detail" pk=task.pk %}"> {{ task.name }} </a></p>
      {% endfor %}
      {% else %}
        <p class="card-text container"> There are no tasks of the type.</p>
      {% endif %}

    </div>
  </div>


  <div class="container">
    <a class="btn btn-warning btn-lg" href="{% url "task_manager:task-types-update" pk=tasktype.pk %}">Update</a>
    <a class="btn btn-danger btn-lg" href="{% url "task_manager:task-types-delete" pk=tasktype.pk %}">Delete</a>
  </div>

{% endblock %}

templates/task_manager/tasktype_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h2>{{ object|yesno:"Update,Create" }} task type!</h2>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}

{% block footer %}
{% endblock %}

templates/task_manager/tasktype_list.html
{% extends "base.html" %}

{% block content %}

  <br>
  <a class="btn btn-success" href="{% url 'task_manager:task-types-create' %}" style="margin-left: 5%;">
      Create new task-type
  </a>
  <p></p>


  <h2 style="margin-left: 13%;" >Task-types: </h2>
    {% for task_type in tasktype_list %}

      <a class="container" href="{% url "task_manager:task-type-detail" pk=task_type.pk %}" style="text-decoration: none;">

      <div class="card text-white bg-dark mb-2" style="max-width: 30rem; margin-left: 100px;">
        <div class="card-header">
          {{ task_type.name }}
        </div>
      </div>

      </a>

      {% empty %}
      <p>There are no task-types...</p>
    {% endfor %}


{% endblock %}

templates/task_manager/worker_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2 class="container"> Are you sure you want to delete the worker? </h2>
  <form action="" method="post">
    {% csrf_token %}

  <div class="container">
    <input type="submit" value="Yes" class="btn btn-danger container">
    <a href="{% url "task_manager:worker-list"  %}" class="btn btn-secondary container">No</a>
  </div>

  </form>
{% endblock %}

templates/task_manager/worker_detail.html
{% extends "base.html" %}

{% block content %}
  <br>
    <h2 class="container"><strong>{{ worker.first_name }} {{ worker.last_name }} ({{ worker.username }})</strong></h2>

  <div class="card mb-3 container" style="padding: 0">
  <div class="row no-gutters">
    <div class="col-md-4">
       <img src="{{ worker.photo_url|default_if_none:'#' }}" alt="{{ worker.username }}" class="container" style="padding: 0"/>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title container"><strong>{{ worker.position.name }}</strong></h5>

        <p class="card-text">Email: {{ worker.email }}</p>
        <p class="card-text">Superuser: {% if  worker.is_superuser %} ✅ {% else %} ❌ {% endif %}</p>
        <p class="card-text">Is active: {% if  worker.is_active %} ✅ {% else %} ❌ {% endif %}</p>
        <p class="card-text">Is staff: {% if  worker.is_staff %} ✅ {% else %} ❌ {% endif %}</p>

  {% if worker.task_set.all %}
          <p class="card-text">Currently, he is involved in such projects </p>
        {% for task in worker.task_set.all %}
          <p class="card-text container">— <a href="{% url "task-manager:task-detail" pk=task.pk %}">{{ task.name }}</a></p>
        {% endfor %}
    {% else %}
          <p class="card-text container">As of this moment, the worker has no task.</p>
    {% endif %}
      <p class="card-text"><small class="text-muted">Joined us on {{ worker.date_joined }}</small></p>
      </div>
    </div>
  </div>
</div>

  <div class="container">
    <a class="btn btn-warning btn-lg" href="{% url "task_manager:worker-update" pk=worker.pk %}">Update</a>
    <a class="btn btn-danger btn-lg" href="{% url "task_manager:worker-delete" pk=worker.pk %}">Delete</a>
  </div>

{% endblock %}

templates/task_manager/worker_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h2>{{ object|yesno:"Update,Create" }} employee </h2>
  <form action="" method="post" novalidate>
    {% csrf_token %}
        {{form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

{% block footer %}
{% endblock %}

templates/task_manager/worker_list.html
{% extends "base.html" %}

{% block content %}


  <br>
  <a class="btn btn-success" href="{% url 'task_manager:worker-create' %}" style="margin-left: 5%;">
      Create new worker
  </a>
  <p></p>


    <h2 class="container" style="margin-bottom: 40px;">
      A detailed description of all employees of our company
    </h2>

    {% if worker_list %}

    <table class="table">
    <tr style="background-color: gray">
      <th>NUMBER</th>
      <th>NAME</th>
      <th>POSITION</th>
      <th>EMAIL</th>
      <th>STAFF STATUS</th>
      <th>ACTIVE</th>
      <th>SUPERUSER</th>
      <th>JOINED DATA</th>
    </tr>

    {% for worker in worker_list %}
      <tr style="background-color: azure">
        <th>{{ worker.id }}</th>
        <th><a href="{% url "task-manager:worker-detail" pk=worker.pk %}">{{ worker.first_name }} {{ worker.last_name }} ({{ worker.username }})</a></th>
        <th>{{ worker.position }}</th>
        <th>{{ worker.email }}</th>
        <th>{{ worker.is_staff }}</th>
        <th>{{ worker.is_active }}</th>
        <th>{{ worker.is_superuser }}</th>
        <th>{{ worker.date_joined }}</th>

      </tr>
    {% endfor %}
    </table>
    {% else %}
      <p>There are no tasks in the service.</p>
    {% endif %}
{% endblock %}